name: Postgres Service Example

on:
  push:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-20.04
    container:
      image: golang

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - run: echo postgres > .pgpass; psql --username=postgres --dbname=postgres --file=01.sql
      env:
        PGHOST: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
